### ISSUE TITLE
Error on fresh clone

### ISSUE THREAD

**Issue by r4881t** [exiled-apes/candy-machine-mint#1]
Hi. This is a good effort. I tried to test it out by following

1. git clone
2. yarn install
3. yarn build
4. yarn start

When I goto localhost:3000 I get an error as shown in screenshot below.

<img width="1680" alt="Screenshot 2021-09-06 at 10 43 49 PM" src="https://user-images.githubusercontent.com/81687400/132248315-353ddf54-89fe-4dd1-80c4-5c67eab20522.png">

**Comment by levicook** [comment]
Ah! This makes perfect sense and boils down to a lack of proper documentation and error handling.
I'll document it properly, but the short term thing to know is this relies on a set of environment variables you can find in App.tsx -- they basically exist to get your app pointed at the right solana network (devnet, mainnet, etc) and your candy-machine accounts.

**Comment by levicook** [comment]
Here are the environment vars you'll need to resolve:
https://github.com/exiled-apes/candy-machine-mint/blob/main/src/App.tsx#L22-L39

The easiest way to handle it is to create a `.env` file with the following keys:
```
REACT_APP_CANDY_MACHINE_CONFIG="redacted"
REACT_APP_CANDY_MACHINE_ID="redacted"
REACT_APP_CANDY_START_DATE=1630422000000
REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://explorer-api.devnet.solana.com
REACT_APP_TREASURY_ADDRESS="redacted"
```

You'll have to fill in the redacted pieces.

**Comment by codesart-4** [comment]
Hey, can you explain what who are values?

I've read solana and spl-token but they never used that names. I have account pubkey (main solana address), candy PDA pubkey. But what are those machine config and machine id and treasury address?

**Comment by ezinaz** [comment]
REACT_APP_CANDY_MACHINE_CONFIG="redacted"
REACT_APP_CANDY_MACHINE_ID="redacted" // the ID that you get back after a successful Candy Machine creation...example:
$ ts-node cli create_candy_machine -k ~/.config/solana/devnet.json -p 1
Done: CANDYMACHINE: H2YZ5uNhANPzE1EqsraVRfdXyFMXvbZijGRpy1aCR9CJ

REACT_APP_CANDY_START_DATE=1630422000000 // unix timestamp to start the minting process
REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://explorer-api.devnet.solana.com
REACT_APP_TREASURY_ADDRESS="redacted" // Wallet public key that was used when creating the candy machine through metaplex command line (upload, create candy machine)

I'm pretty sure that I know what these are except for the first one, see above.

**Comment by ezinaz** [comment]
So that being said what is this one?

REACT_APP_CANDY_MACHINE_CONFIG="redacted"

**Comment by gafotech** [comment]
> So that being said what is this one?
> 
> REACT_APP_CANDY_MACHINE_CONFIG="redacted"

I think it's the config value inside the `.cache/temp` output created by the cli upload command.

```json
{"program":{"uuid":"APjkMe","config":"APhgMeJV....redacted.....7L3yApd3"}, ... }
```

I'm not sure but I think it's this.

**Comment by ezinaz** [comment]
It was thank you @gafotech !

**Comment by r4881t** [comment]
Reopening as it needs some more details.

**Comment by levicook** [comment]
Yup, definitely needs additional docs. Will aim to update them tomorrow

**Comment by halaprix** [comment]
> > So that being said what is this one?
> > REACT_APP_CANDY_MACHINE_CONFIG="redacted"
> 
> I think it's the config value inside the `.cache/temp` output created by the cli upload command.
> 
> ```json
> {"program":{"uuid":"APjkMe","config":"APhgMeJV....redacted.....7L3yApd3"}, ... }
> ```
> 
> I'm not sure but I think it's this.

How could that work ? There's a 
`const config = new anchor.web3.PublicKey(
  process.env.REACT_APP_CANDY_MACHINE_CONFIG!
);`

so It has to be a public address, not a JSON file. I mean I'd love it to work this way but it doesn't ;) (at least form me)

**Comment by levicook** [comment]
We'll continue adding details, but have a good first pass from @novaraptur so closing this since we went from zero to one.

**Comment by ohaddahan** [comment]
`metaplex upload ./assets --env devnet --keypair ~/.config/solana/devnet.json`


```
Processing file: 0
initializing config
initialized config for a candy machine with uuid: <REACT_APP_CANDY_MACHINE_ID>
Started awaiting confirmation for <CONFIRM_CODE>
REST null result for <CONFIRM_CODE> null
Resolved via websocket { err: null }
Returning status { err: null, slot: <SLOT_NUM>, confirmations: 0 }
Latency <CONFIRM_CODE> 0.6189999580383301
transaction for arweave payment: {
  txid: <CONFIRM_CODE>,
  slot: <SLOT_NUM>
}
trying to upload 0.png: <NAME>
File uploaded: https://arweave.net/<ID>
setting cache for  0
Writing indices 0-0
Done. Successful = true. If 'false' - rerun
```


`cat .cache/devnet-temp`

```json
{
   "program":{
      "uuid":"<REACT_APP_CANDY_MACHINE_ID>",
      "config":"<REACT_APP_CANDY_MACHINE_CONFIG>"
   },
   "items":{
      "0":{
         "link":"https://arweave.net/<ID>",
         "name":"<NAME>",
         "onChain":true
      }
   }
}
```

Is this the right mapping? Might be worth it to be more explicit and avoid unneeded questions.

**Comment by ohaddahan** [comment]
`metaplex create_candy_machine  --env devnet --keypair ~/.config/solana/devnet.json` this part is missing from the guide.

**Comment by bennbolton** [comment]
not sure if this is relevant here, I'm having a similar problem, everywhere mentions the .cache/temp file which will provide all necessary information. For me I got a successful upload to candy machine but no .cache/temp file has been created. only a .cache/devnet-example which does not provide all the needed info
