### ISSUE TITLE
PublicKeys Hardcoded

### ISSUE THREAD

**Issue by juanpablom** [exiled-apes/candy-machine-mint#10]
Hi, sorry i'm a newbie, i don't know where to find this PublicKeys (i have the keys for .env only) .
It's in candy-machine.ts file.
thanks!

```
export const CANDY_MACHINE_PROGRAM = new anchor.web3.PublicKey(
  "cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ"
);

const SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID = new anchor.web3.PublicKey(
  "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
);

const TOKEN_METADATA_PROGRAM_ID = new anchor.web3.PublicKey(
  "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
);

```

**Comment by halaprix** [comment]
These are Solana and Metaplex specific programs addresses + the "main" candy machine (to rule them all :) ) from Metaplex.
You can find the same addresses harcoded in the CLI tool.

cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ - https://solscan.io/account/cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ

ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL - https://spl.solana.com/associated-token-account

metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s - https://docs.phantom.app/integrating/tokens/non-fungible-tokens

**Comment by juanpablom** [comment]
great thank you @halaprix
