### ISSUE TITLE
Minting failed! Please try again!

### ISSUE THREAD

**Issue by cdric** [exiled-apes/candy-machine-mint#105]
When trying to mint I am getting the following error:
Minting failed! Please try again!

What can be causing this?
I don't seems to find log to investigate. Where can I find the console log so I could probably share more information.

I was able to setup a different candy matching yesterday and I was able to mint...

**Comment by cdric** [comment]
Closing this as my issue is gone.

**Comment by WildCroc** [comment]
How did you solve it? Im having the same problem

**Comment by sswils211** [comment]
I am also having this problem, but I am unsure of the solution
