### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by halaprix** [exiled-apes/candy-machine-mint#11]
When I start the developement server I get a `Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'digest')` . 

I'm able to connect the wallet and that's what I get next. Tried both on mainnet and devnet. The `candy-machine.ts` is untouched all the values are default.

It get's the provider and fails in the line #163 @ fetchIdl()

       160 |   preflightCommitment: "recent",
       161 | });
       162 | 
     > 163 | const idl = await anchor.Program.fetchIdl(
    ^  164 |   CANDY_MACHINE_PROGRAM,
       165 |   provider
       166 | );

**Comment by nQuery512** [comment]
Same problem here ;)

**Comment by halaprix** [comment]
I have a workaround, but it won't work for all users. 

I switched from Ubuntu (WSL2) to Windows 10, works like a charm.

It seems to be a problem with `@project-serum/anchor` but I didn't dig deeper as for now I'll just use the easy fix.

**Comment by nQuery512** [comment]
Found this, might be linked ?
https://stackoverflow.com/questions/57146558/typeerror-digest-of-undefined-in-development-environment

**Comment by halaprix** [comment]
> Found this, might be linked ? Currently I'm building on a vps, will try on local
> https://stackoverflow.com/questions/57146558/typeerror-digest-of-undefined-in-development-environment
> 
> Seems like it solved it to me,
> 
> **Solution**:
> Put a SS certificate or run it on localhost

That fixed it!

**Comment by philipperemy** [comment]
@halaprix which commands did you run to make it work?
