### ISSUE TITLE
A seed constraint was violated

### ISSUE THREAD

**Issue by jackprescott** [exiled-apes/candy-machine-mint#139]
Awesome project! I'm having one issue, though. I made it all the way through to the end, but when I try to actually mint the NFT, my Phantom Wallet says "Transaction may fail to confirm", and then when I click approve, it fails, and the website gives a dropdown notification that "A seed constraint was violated". Do you have any idea why this might be happening? I followed the steps for modifying my .env.local file very closely.

**Comment by stephen-wagner** [comment]
Any update on this? I'm facing the same issue.

**Comment by abra-ham** [comment]
Hey all. I was able to solve this by making sure that the shares of all creators sum up to 100 and that the seller fees are bigger than 0.

This problem arises from the json file that describes your nfts

**Comment by Leo02607** [comment]
did anyone solve this error?
 it is not related with seller fees and  creators percentages.

**Comment by PyMax** [comment]
Hello. Please check your params in .env file.
REACT_APP_CANDY_MACHINE_CONFIG needs to be with public key when you upload assets in metaplex.
REACT_APP_CANDY_MACHINE_ID it is public key which shows after create_candy_machine command.

**Comment by summerplaybook** [comment]
Hey all! Any progress on this? I have triple checked my .env file and all the parameters are correct and still getting this issue.
I also agree that it doesn't seem to be related to sellers fees or creator percentages.
