### ISSUE TITLE
Invalid Account Discriminator

### ISSUE THREAD

**Issue by brandonculver** [exiled-apes/candy-machine-mint#15]
Getting invalid account discriminator when trying to get the candy store state. This is the devnet, I know its setup and working correctly. I was able to mint via command line and see the nft in the dev minter wallet.

Is this an ID error?

The only ids in my cache file are:

```  "program": {
    "uuid": "CC8R65",
    "config": "CC8R653SGidJkTFEoWyzq8GB... <-- intentionally truncated
    }
```
I originally tried using the uuid as the REACT_APP_CANDY_MACHINE_ID, but the app did not like that. I then just copied the config as the ID as well and everything seemed to work until it tried to fetch the state.

I have not modifed the base app other than the .env, I have tried this on both windows and macos

![screenshot](https://user-images.githubusercontent.com/2267955/132410186-f70f9c2f-b794-45c5-aae2-4a3a532e30d8.png)

**Comment by brandonculver** [comment]
I am closing this but in case anyone else wonders. When you run `metaplex create_candy_machine` it returns and ID in the command prompt. That is what goes in the candy machine id in the .env file. The candy machine config is what is in the cache.

Its strange, metaplex is able to do everything including mint without that ID since the cache does not save it.

It might be a good idea to document the create_candy_machine and set_start_date commands somewhere.

**Comment by joaoh82** [comment]
I am getting this just now.

**Unhandled Rejection (Error): Invalid account discriminator**

<img width="1060" alt="Screen Shot 2021-09-08 at 21 16 23" src="https://user-images.githubusercontent.com/208517/132571207-7e769bd5-f3a4-44f1-b2cd-827217271b9a.png">

Dont really know what to do.

My `.env` looks like this:
```
REACT_APP_CANDY_MACHINE_CONFIG="<program.config from .cache/devnet-temp>"
REACT_APP_CANDY_MACHINE_ID="<program.config from .cache/devnet-temp>"
REACT_APP_CANDY_START_DATE=1631462400 # Sun Sep 12 2021 18:00:00 GMT+0200 (Central European Summer Time)
REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://api.devnet.solana.com
REACT_APP_TREASURY_ADDRESS="<MY_SOLANA_WALLET>"
```

**Comment by mehtaabGill** [comment]
> I am getting this just now.
> 
> 
> 
> **Unhandled Rejection (Error): Invalid account discriminator**
> 
> 
> 
> <img width="1060" alt="Screen Shot 2021-09-08 at 21 16 23" src="https://user-images.githubusercontent.com/208517/132571207-7e769bd5-f3a4-44f1-b2cd-827217271b9a.png">
> 
> 
> 
> Dont really know what to do.
> 
> 
> 
> My `.env` looks like this:
> 
> ```
> 
> REACT_APP_CANDY_MACHINE_CONFIG="<program.config from .cache/devnet-temp>"
> 
> REACT_APP_CANDY_MACHINE_ID="<program.config from .cache/devnet-temp>"
> 
> REACT_APP_CANDY_START_DATE=1631462400 # Sun Sep 12 2021 18:00:00 GMT+0200 (Central European Summer Time)
> 
> REACT_APP_SOLANA_NETWORK=devnet
> 
> REACT_APP_SOLANA_RPC_HOST=https://api.devnet.solana.com
> 
> REACT_APP_TREASURY_ADDRESS="<MY_SOLANA_WALLET>"
> 
> ```
> 
> 
> 
> 

change REACT_APP_CANDY_MACHINE_ID to the ID that is printed to the console when you create the candy machine in the console.
