### ISSUE TITLE
8 byte discriminator did not match what was expected

### ISSUE THREAD

**Issue by Wdeacon20** [exiled-apes/candy-machine-mint#152]
I get the error "8 byte discriminator did not match what was expected" when attempting to mint on the Devnet local. Any ideas?

My config # matches on both candy machine & metaplex.

**Comment by thetfudgecoder** [comment]
hey, did you manage to get it fixed?

**Comment by mattlm0831** [comment]
@thetfudgecoder @Wdeacon20 did either of you manage to figure this out? I am trying to test minting on devnet as well.

**Comment by XScriptingMachineX** [comment]
> @thetfudgecoder @Wdeacon20 did either of you manage to figure this out? I am trying to test minting on devnet as well.

Did you get it fixed?

**Comment by dev-tom-0108** [comment]
Hi, I also have the bug like this. what is the solution? plz explain me.

**Comment by black-wyvern-dev** [comment]
Please code review and add #[account(zero)] instead #[account(mut)]
