### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by thetfudgecoder** [exiled-apes/candy-machine-mint#160]
Hey guys. Most likely it's my configuration issue, but if not, maybe you could help me to fix this. It starts fine, I can connect different wallets, but right after that I get this error

Here is the config of my candy machine temp file (I replaced real keys with placeholders)
```
{
   "program":{
      "uuid":"<UUID>",
      "config":"<CANDY_MACHINE_CONFIG>"
   },
   "items":{
      "0":{
         "link":"https://arweave.net/-Q-Z4em7xNsWikGM5w8j6IZqoMZUok8OIEJ_SJ9Z4Ls",
         "name":"Your Collection #1",
         "onChain":true
      }
   },
   "env":"devnet",
   "cacheName":"temp",
   "authority":"<WALLET_PUBLIC_KEY>",
   "candyMachineAddress":"<CANDY_MACHINE_ID>",
   "startDate":1636018073.02
}
```

And this is how I configured .env
```
REACT_APP_CANDY_MACHINE_CONFIG=<CANDY_MACHINE_CONFIG>
REACT_APP_CANDY_MACHINE_ID=<CANDY_MACHINE_ID>
REACT_APP_TREASURY_ADDRESS=<WALLET_PUBLIC_KEY>
REACT_APP_CANDY_START_DATE=1636018073.02

REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://explorer-api.devnet.solana.com
```

Still don't understand if it's my bad configuration or there is a real issue executing:
```
const idl = await anchor.Program.fetchIdl(
    CANDY_MACHINE_PROGRAM,
    provider
  );
```

<img width="1030" alt="Screen Shot 2021-11-06 at 12 28 28 AM" src="https://user-images.githubusercontent.com/93630881/140504094-9574c736-b1e1-4c13-a903-45779b1d4f7e.png">

**Comment by ccamaleon5** [comment]
I have got the same error

**Comment by thetfudgecoder** [comment]
I fixed it. For me it was wrong environment variables. HackMD tutorial missed one step to create candy machine. And also start date must be exact same.

try to follow this guide, it helped me https://dev.to/devindxdeveloper/creating-an-nft-on-solana-with-metaplex-candy-machine-4agp

**Comment by Sickde** [comment]
anyone got a solution for that?

**Comment by Sickde** [comment]
@thetfudgecoder do you know which step was missing or which step was the problem i started from scratch and keep getting this error.

**Comment by danicuki** [comment]
I had this issue when accessing the local address with `http://0.0.0.0:3000/`
When I changed to `http://localhost:3000/` everything worked just fine
