### ISSUE TITLE
How can I mint NFT's without browser

### ISSUE THREAD

**Issue by Qu1rinUs** [exiled-apes/candy-machine-mint#162]
I created a candy machine. Can I use commands for mint NFT's without everytime is opened browser? 
How I understood, first candy machine creates and only after that React app in browser. I want to buy my NFTs with Solana CLI or Metaplex maybe. without Frontend.

**Comment by kafinsalim** [comment]
metaplex candy machine cli have `mint_one_token` sub command

https://github.com/metaplex-foundation/metaplex/blob/a733ebb2262da68d3400f96861fe6ad199e48c3c/js/packages/cli/README.md
