### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'candyMachineAddress')

### ISSUE THREAD

**Issue by 7asuni** [exiled-apes/candy-machine-mint#196]
Hey there I am right now at the Mainnet-beta and try to upload a collection... but the command :
"ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --keypair ~\metaplex.config\solana\mainnet.json --price 0.005 --date "15 Dec 2021 00:00:00 EST" shows me an error.... all the other command before works well without any problems.
![tempsnip](https://user-images.githubusercontent.com/94254018/146081729-224ba74c-7a2b-448a-8bb8-4baec830ba0e.png)

Can you guys please help me :(? On the devnet everthing went right...

**Comment by Khushhal23** [comment]
How to solve this?
