### ISSUE TITLE
Unhandled Rejection (Error): Account does not exist pdbvT2TQw6dJEdKLc43jxFND3opEFeDx8CKC3A5GdQD

### ISSUE THREAD

**Issue by 7asuni** [exiled-apes/candy-machine-mint#198]
Hello guys I am on my last step to mint the NFTs at the local host... but when I start the candymachine I get this error on my browser... when I was testing it on the devnet everything went right..

Do you have an idea what am I missing out :(? I am really getting frustrated.  

Please find the pic of the error below.
![error cm](https://user-images.githubusercontent.com/94254018/146273667-213fe3ec-a418-4c2c-b505-929fb808a769.png)

**Comment by OlajideOgun** [comment]
how did you solve this
