### ISSUE TITLE
Is there a plan to add disconnect wallet button?

### ISSUE THREAD

**Issue by codesart-4** [exiled-apes/candy-machine-mint#20]
Correct me if Im wrong, this repo gets price from candymachine on chain data right? Similarly it can also get data for current mints done and show it in frontend, right? Any timeline on when this can be implemented in this project?

Also wallet disconnect feature is really needed, imo.

**Comment by adrzadrz** [comment]
the `getCandyMachineState` already returns the number of items remaining.
`const { candyMachine, goLiveDate, itemsRemaining } = await getCandyMachineState(anchorWallet, candyMachineId, connection )`

so you could just show itemsRemaining on your total mints

**Comment by codesart-4** [comment]
Yep, figured it out and it's working. But dunno how to disconnect wallet? Any ideas?
