### ISSUE TITLE
Unhandled Rejection (Error): Invalid account discriminator

### ISSUE THREAD

**Issue by raghibislam** [exiled-apes/candy-machine-mint#22]
![image](https://user-images.githubusercontent.com/46419375/132698551-1bb015b3-c838-4e7b-9cd4-6952cd300f74.png)
 Every time I open my application this happens.

**Comment by PixlFrogs** [comment]
You have to run metaplex create_candy_machine --keypair <YOURKEYPAI> to get an ID. That's the ID you stick in the .env file

**Comment by raghibislam** [comment]
Yes solved 
Thanks !!

**Comment by bhupenchn** [comment]
```$ metaplex create_candy_machine -k ~/.config/solana/devnet.json
(node:24021) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'program' of undefined
    at /snapshot/js/packages/cli/build/cli.js:423:63
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.next (/snapshot/js/packages/cli/build/cli.js:45:53)
    at fulfilled (/snapshot/js/packages/cli/build/cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:24021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

Running the create_candy_machine throws error.
I am on ubuntu18.04, had created the metaplex cli tool with the following command
`npx pkg . -d --targets node14-linux-x64 --output bin/linux/metaplex`

What am I doing wrong?

**Comment by rohanm19** [comment]
Same as above . on windows it throws this error


`
(node:10072) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_bn' of undefined
    at isPublicKeyData (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:111:16)
    at new PublicKey (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:130:9)
    at C:\snapshot\js\packages\cli\build\cli.js:423:26
    at step (C:\snapshot\js\packages\cli\build\cli.js:64:23)
    at Object.next (C:\snapshot\js\packages\cli\build\cli.js:45:53)
    at fulfilled (C:\snapshot\js\packages\cli\build\cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:10072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
