### ISSUE TITLE
Error when minting: A has_one constraint was violated

### ISSUE THREAD

**Issue by zerosdontcount** [exiled-apes/candy-machine-mint#25]
After generating candy machine and setting the start date, the front-end application when hitting mint shows in a popup error that says "A has_one constraint was violated"

In the JS console the following error is rendered:

`index.js:1 Transaction simulation failed: Error processing Instruction 4: custom program error: 0x8d 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
    Program log: Instruction: InitializeMint
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2390 of 200000 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
    Program log: Transfer 2039280 lamports to the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the associated token account to the SPL Token program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Initialize the associated token account
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3449 of 179576 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 24522 of 200000 compute units
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
    Program log: Instruction: MintTo
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2879 of 200000 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 14724 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:4049
sendEncodedTransaction @ connection.ts:3574
async function (async)
sendEncodedTransaction @ connection.ts:3565
sendRawTransaction @ connection.ts:3537
sendAndConfirmRawTransaction @ send-and-confirm-raw-transaction.ts:27
send @ provider.ts:112
async function (async)
send @ provider.ts:99
rpc @ rpc.ts:19
mintOneToken @ candy-machine.ts:251
async function (async)
mintOneToken @ candy-machine.ts:242
onMint @ Home.tsx:60
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react_devtools_backend.js:4049 Translating error Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x8d
    at Connection.sendEncodedTransaction (connection.ts:3577)
    at async Connection.sendRawTransaction (connection.ts:3537)
    at async sendAndConfirmRawTransaction (send-and-confirm-raw-transaction.ts:27)
    at async Provider.send (provider.ts:112)
    at async Object.rpc [as mintNft] (rpc.ts:19)
    at async mintOneToken (candy-machine.ts:251)
    at async onMint (Home.tsx:60)`
    
    
Any tips on this? Thanks!

**Comment by dubin-s** [comment]
Means you have the wrong account.

**Comment by marsturbate** [comment]
How you fixed this?

**Comment by zerosdontcount** [comment]
I restarted everything from scratch and it worked

**Comment by brantchoate** [comment]
having this problem too..
