### ISSUE TITLE
Unhandled Rejection (Error): Invalid account discriminator

### ISSUE THREAD

**Issue by rohanm19** [exiled-apes/candy-machine-mint#26]
Hi I get the following error on running yarn run: 

Unhandled Rejection (Error): Invalid account discriminator

`
AccountClient.fetch
E:/src/program/namespace/account.ts:135
  132 | /**
  133 |  * Returns an instruction for creating this account.
  134 |  */
> 135 | async createInstruction(signer, sizeOverride) {
      | ^  136 |     const size = this.size;
  137 |     return SystemProgram.createAccount({
  138 |         fromPubkey: this._provider.wallet.publicKey,
View compiled
async getCandyMachineState
E:/Blockchains/Solana/NFTs/candy-machine-mint/src/candy-machine.ts:175
  172 |    program,
  173 |  }
  174 | 
> 175 |  const state: any = await program.account.candyMachine.fetch(candyMachineId);
      | ^  176 |  const itemsAvailable = state.data.itemsAvailable.toNumber();
  177 |  const itemsRedeemed = state.itemsRedeemed.toNumber();
  178 |  const itemsRemaining = itemsAvailable - itemsRedeemed;`

**Comment by raghibislam** [comment]
seems your .env is wrong

**Comment by crypt0miester** [comment]
did you metaplex upload?

**Comment by rohanm19** [comment]
I did metaplex upload, yes.

Following is my env. Although my arweave wallet address is different. Not sure how the metaplex cli uploads without arweave wallet information. (Sorry i am a noob in metaplex and rust, although i am decently well versed with js, tsx and everything react - context, hooks etc.)

REACT_APP_CANDY_MACHINE_CONFIG=<My Sol Address>
REACT_APP_CANDY_MACHINE_ID=<My Sol Address>
REACT_APP_CANDY_START_DATE=1630422000000
REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://explorer-api.devnet.solana.com
REACT_APP_TREASURY_ADDRESS=<My 2nd sol address>

**Comment by odineH** [comment]
have the same problem here, any help?:D thanks in advance

**Comment by LGNorris** [comment]
Current having the same issue. Have ran metaplex upload and successfully upload and also then taken env var from config in .cache/temp.

**Comment by rohanm19** [comment]
Is this the right sequence?

1. Run metaplex upload (as per hackmd guide this also runs create_candy_machine?) Not sure if we need to run the create candy machine manually
2. From the cache get the candy machine id
3. The candy machine config is actually the sol address from the keypair json

Can someone confirm?

**Comment by trust0212** [comment]
Read.md file is incorrect.
You need to run `metaplex create_candy_machine` command and copy the output address and paste it to candy_machine_id file of .env file

**Comment by rohanm19** [comment]
Thanks.

One more question: the readme says we need to provide json and pngs . The json structure is as described in the metaplex standard.  Also it says the metaplex upload command uploads to arweave and associates with the candy machine (I am assuming i will need to create candy machine before metaplex upload?).

One of the attribute in json is the uri. How can i get an uri before uploading it to arweave?

**Comment by rohanm19** [comment]
Figured it out :)

**Comment by easydeveloppement** [comment]
@rohanm19 could you explain it ? thank you :)
