### ISSUE TITLE
Adding option to let customer mint more than one token at a time?

### ISSUE THREAD

**Issue by WilliamRT95** [exiled-apes/candy-machine-mint#32]
Will be great, almost necessary to let people choose how many tokens they mint at once. Aldo that may be an issue from metaplex itself?

**Comment by levicook** [comment]
Hey! Interesting idea and common ask. This is indeed a core mextaplex feature to consider. I'm not sure how likely it will ever land on the roadmap either, since it's conceptually not what the candy machine aims to be. (there will be lots more smart contracts though!)

**Comment by levicook** [comment]
To elaborate; the smart contract models a real world candy-machine:
- one transaction
- coins go in
- one thing comes out

**Comment by noconstruct** [comment]
> Hey! Interesting idea and common ask. This is indeed a core mextaplex feature to consider. I'm not sure how likely it will ever land on the roadmap either, since it's conceptually not what the candy machine aims to be. (there will be lots more smart contracts though!)

Hey what exactly does the candy machine aim to be ? If not a minting randomizer ?

**Comment by levicook** [comment]
> Hey what exactly does the candy machine aim to be ? If not a minting randomizer ?

Did you catch the last reply? Looks like we might have been typing at the same time, so maybe not.

**Comment by levicook** [comment]
WRT Randomness -- the candy machine program is not random at all. It dispenses your inventory by moving down a list. If you need randomness, you need to make sure that you're loading it up with a randomly ordered set of assets.

**Comment by noconstruct** [comment]
Just read up and reacted, thanks for the clarification of what exactly the candy machine is. The concept seems more sustainable Than the current ethereum meta. But is also very confusing for an ethereum maxi such as myself.

**Comment by WilliamRT95** [comment]
Alright, excited for the future of this project! Thanks a lot!

**Comment by levicook** [comment]
> Just read up and reacted, thanks for the clarification of what exactly the candy machine is. The concept seems more sustainable Than the current ethereum meta. But is also very confusing for an ethereum maxi such as myself.

I still need to learn more about the ETH ways. And there are a lot of additional Solana powered smart contracts coming. The candy machine is a relatively specific solution to a specific problem; that I'm working to help people understand better.

**Comment by WilliamRT95** [comment]
@levicook Hey! Im sure you already know, but I just checked office hours from yesterday and Jordan explains how to fix the minting multiple transactions at once. It seems fairly easy, but I still cannot make it work😭

**Comment by ClockRide** [comment]
> @levicook Hey! Im sure you already know, but I just checked office hours from yesterday and Jordan explains how to fix the minting multiple transactions at once. It seems fairly easy, but I still cannot make it work😭

May you give a link to the explanation, please (or explain it yourself). Maybe we'll be able to help you :)
I'm interested in implementing this feature myself tbh.

**Comment by WilliamRT95** [comment]
Sure, 
Info from Jordan's twitter account:
Office hours link: https://solanalabs.zoom.us/rec/play/eNyl10xJ8TVBI1u6xH0ORqnqn6UX9CWy8EWmyKd3rfFx4P4KtcAlbynAfmZGPBOwvQCB8A8y7AcUZOk.1sp9QUnXzDHpbBqj?continueMode=true&_x_zm_rtaid=IYsU2p03RnOdAGiDkXXpKQ.1631526669283.df8c844d5447fdc6c42add80607be3bf&_x_zm_rhtaid=272

Password: 0MYbiD^H

minute: 45

**Comment by dimeznft** [comment]
@WilliamRT95 Hi there, did you ever get this to work? just curious what was getting you stuck, thanks!
