### ISSUE TITLE
A has_one constraint was violated

### ISSUE THREAD

**Issue by richardj97** [exiled-apes/candy-machine-mint#42]
I get this error 'A has_one constraint was violated' when trying to mint on devnet. Any ideas? Do you think its because I'm on a devnet?

**Comment by PnW1** [comment]
I am having the same issue.

**Comment by trust0212** [comment]
same issue

**Comment by AbucoAnd** [comment]
here too :( any solution?

**Comment by richardj97** [comment]
Nope. I'm hoping @levicook can provide an answer

**Comment by Fahad-pnw** [comment]
Devnet isn't the issue. I've had that error as well. When that message appeared at the bottom of the MINT screen for me, it was because my treasury address within the .env file was not set correctly. It should be the same as the Dev wallet that you created. 

--itsdigidal
:)

**Comment by AbucoAnd** [comment]
@Fahad-pnw it worked for me!^^
