### ISSUE TITLE
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit

### ISSUE THREAD

**Issue by richardj97** [exiled-apes/candy-machine-mint#47]
I receive this error when trying to do the metaplex upload on the mainnet. I have check my balance and I have 2.9 SOL (Using solana balance), which is more than enough to upload, just not sure why this is happening? Any ideas?

[
![image](https://user-images.githubusercontent.com/28660688/133236881-9e1ebe45-9a54-4c74-a2f4-36470cfb3bab.png)
](url)

**Comment by levicook** [comment]
A little hard to see the screenshot; posting the text version would be helpful. But it looks like there's a balance issue relative to the key being used by the cli. Make sure when you check your balance and invoke the cli these things are the same. eg:

```
solana balance -k my-key.json
metaplex upload ./assets -k my-key.json
```

You can also review and control what defaults are being used with:
`solana config get` and `solana config set` (both accept `--help`)

**Comment by richardj97** [comment]
Yeah I've manage to sort the issue thanks. I'm having timeout errors at the moment on the mainnet but i think its because solana mainnet is down at the moment
