### ISSUE TITLE
Countdown issue

### ISSUE THREAD

**Issue by richardj97** [exiled-apes/candy-machine-mint#50]
Hello,

Is there any reason why the countdown doesn't work? It works when you set the date as:

```
<Countdown
  date={Date.now() + 5000}
  renderer={renderCounter}
/>
```

But not as:

```
<Countdown
  date={startDate}
  renderer={renderCounter}
/>
```

**Comment by adrzadrz** [comment]
the `startDate` is updated with the candy machine's date, so it's maybe why your value is not right

**Comment by richardj97** [comment]
> the `startDate` is updated with the candy machine's date, so it's maybe why your value is not right

What solution did you implement to fix this? It seems to be the original code

**Comment by kyonym** [comment]
My date is correct and the counter is acting the same way  @richardj97 describes.

**Comment by the-wuh** [comment]
add ```000``` to REACT_APP_CANDY_START_DATE

**Comment by kyonym** [comment]
@the-wuh instead of the UNIX time or before the UNIX time?

**Comment by richardj97** [comment]
> add `000` to REACT_APP_CANDY_START_DATE

Wow something as simple as that fixes it haha. Thanks :)

**Comment by SeanOverton** [comment]
Like prepend 000 to the REACT_APP_CANDY_START_DATE??
so instead of REACT_APP_CANDY_START_DATE=1632355920
do REACT_APP_CANDY_START_DATE=0001632355920??

**Comment by SeanOverton** [comment]
nevermind its add them ahaha my bad so this
1632355920000

**Comment by SeanOverton** [comment]
gotcha
