### ISSUE TITLE
Getting a type error when trying to start the candy machine locally

### ISSUE THREAD

**Issue by kamilsadik** [exiled-apes/candy-machine-mint#6]
After cloning the repo I did:
yarn install
yarn build
yarn start

I created a .env file in the /src/ directory as recommended in [this issue](https://github.com/exiled-apes/candy-machine-mint/issues/1) (though I'm not entirely sure what to put in for CANDY_MACHINE_ID).

When I run yarn start, I get this error:

![Screen Shot 2021-09-06 at 14 17 48](https://user-images.githubusercontent.com/75034988/132251947-d98d780d-6d8f-4988-ad0b-6c0fde0067b4.png)

**Comment by ajobi-uhc** [comment]
Getting the same issue is it a dotenv config issue?
