### ISSUE TITLE
Does the metaplex cli upload your images as well?

### ISSUE THREAD

**Issue by justinpezzack** [exiled-apes/candy-machine-mint#71]
Running through the source code, there is no place that the metaplex cli uploads your image and edits your X.json file before adding it to the Candy Machine, am I missing something or do you need to manually upload your images, edit your json and then push your X.jsons after?

**Comment by yalis** [comment]
The upload command does that.
Take a look at the readme file:
https://github.com/metaplex-foundation/metaplex/tree/master/js/packages/cli

**Comment by justinpezzack** [comment]
Yup I'm a monkey, thanks yalis.
