### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read properties of null (reading 'toNumber')

### ISSUE THREAD

**Issue by walter-grace** [exiled-apes/candy-machine-mint#76]
I keep getting this error, everything seems to be working on the UI part but this seems to be my issue more times then not. Is it a clock/start_date error? Metaplex sometimes doesnt give me a unix code so maybe I am converting it wrong.

`getCandyMachineState
src/candy-machine.ts:180
async
src/Home.tsx:136
`

**Comment by daverees4** [comment]
Is it possible you're confusing the UNIX timestamp needed here (eg. 1632657239) and and a JS timestamp (which is in milliseconds eg. 1632657384661).  I just did this :)

**Comment by walter-grace** [comment]
It was a timecode issue please make sure to add -d that fixed my issue

**Comment by valtumi** [comment]
I had that issue. The problem was that `"startDate"` was missing from `./.cache/devnet-temp` file. After running `update_candy_machine` command from here https://docs.metaplex.com/create-candy/update-cm it all worked like a charm.
