### ISSUE TITLE
Issue with 'metaplex create_candy_machine'  command

### ISSUE THREAD

**Issue by pointersolana** [exiled-apes/candy-machine-mint#9]
In order to populate my .env file I need to run the command below v. But I keep getting this error. The file for my wallet is correct.

**metaplex create_candy_machine -k ~/.config/solana/devnet.json**

(node:60861) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'program' of undefined
    at /snapshot/js/packages/cli/build/cli.js:574:66
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.next (/snapshot/js/packages/cli/build/cli.js:45:53)
    at fulfilled (/snapshot/js/packages/cli/build/cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by SevenIndirecto** [comment]
I needed a `.cache/temp` file first, which I generated using `metaplex upload ...` beforehand, then it worked.

**Comment by SevenIndirecto** [comment]
Btw the steps I went through to be able to execute via the Mint button are:

```
$ metaplex upload ./assets --url https://api.devnet.solana.com --keypair ~/my-solana-wallet/my-keypair.json
# This gets your the CONFIG pubkey from .cache/temp (program.config)

$ metaplex create_candy_machine -k ~/my-solana-wallet/my-keypair.json -p 2 -e devnet
# This gets you the pubkey for REACT_APP_CANDY_MACHINE_ID

$ metaplex set_start_date -k ~/my-solana-wallet/my-keypair.json -d "04 Dec 2020 00:12:00 GMT" -e devnet
```

**Comment by pointersolana** [comment]
This solved the issue indeed @SevenIndirecto. Tyvm!

**Comment by zakaria-ahmed** [comment]
> Btw the steps I went through to be able to execute via the Mint button are:
> 
> ```
> $ metaplex upload ./assets --url https://api.devnet.solana.com --keypair ~/my-solana-wallet/my-keypair.json
> # This gets your the REACT_APP_CANDY_MACHINE_CONFIG pubkey from .cache/temp (program.config)
> 
> $ metaplex create_candy_machine -k ~/my-solana-wallet/my-keypair.json -p 2 -e devnet
> # This gets you the pubkey for REACT_APP_CANDY_MACHINE_ID
> 
> $ metaplex set_start_date -k ~/my-solana-wallet/my-keypair.json -d "04 Dec 2020 00:12:00 GMT" -e devnet
> ```

there is no -e flag for metaplex create_candy_machine ?

**Comment by zakaria-ahmed** [comment]
never mind had to update the metaplex binary. although this is a lot more clear then the docs on readme
