### ISSUE TITLE
Error: No 8 byte discriminator was found on the account

### ISSUE THREAD

**Issue by Elonat9** [exiled-apes/candy-machine-mint#92]
Hi everyone !

I got this error when I try to mint my NFT. 
In Dev tool got this : 
index.js:1 Transaction simulation failed: Error processing Instruction 4: custom program error: 0xa1 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
    Program log: Instruction: InitializeMint
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2390 of 200000 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
    Program log: Transfer 2039280 lamports to the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the associated token account to the SPL Token program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Initialize the associated token account
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3449 of 179576 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 24522 of 200000 compute units
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
    Program log: Instruction: MintTo
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2879 of 200000 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0xa1
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 5303 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0xa1

Any Ideas of the problem ? 
Thanks for the read !

**Comment by Elonat9** [comment]
I forgot to put this, it was on browser dev tool too : 
Translating error Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0xa1
    at Connection.sendEncodedTransaction (connection.ts:3668)
    at async Connection.sendRawTransaction (connection.ts:3628)
    at async sendAndConfirmRawTransaction (send-and-confirm-raw-transaction.ts:27)
    at async Provider.send (provider.ts:112)
    at async Object.rpc [as mintNft] (rpc.ts:19)
    at async mintOneToken (candy-machine.ts:259)
    at async onMint (Home.tsx:64)

**Comment by SethCalkins** [comment]
@Elonat9 What was the issue? I'm having the same problem.
